In [ ]:
# 출발지연과 도착지연의 상관관계를 파악하고자 한다.

In [1]:
import pandas as pd

In [2]:
flight = pd.read_excel('C:/Users/ICT01_14/Desktop/flight_status_06_09_2.xlsx')

In [3]:
a= flight[flight.arrived_airport_name == '제주']# & flight.airline_name == '대한항공']
a[a.airline_name =='대한항공'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1347 entries, 18 to 14776
Data columns (total 14 columns):
flight_num               1347 non-null object
airline_name             1347 non-null object
airport_code             1347 non-null object
city_code                1347 non-null object
arrived_airport_name     1347 non-null object
boarding_airport_name    1347 non-null object
scheduled_time           1347 non-null int64
changed_time             1299 non-null float64
inout_code               1347 non-null object
flight_status_eng        1220 non-null object
flight_status_kor        1220 non-null object
delay_yn                 1347 non-null object
create_date              1347 non-null datetime64[ns]
update_date              1347 non-null object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 157.9+ KB

In [4]:
flight

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14776,KE1273,대한항공,CJU,GMP,제주,서울/김포,2140,2126.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00
14777,7C147,제주항공,CJU,GMP,제주,서울/김포,2145,2135.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00
14778,TW9816,티웨이항공,CJU,TAE,대구,제주,2155,2158.0,O,DEPARTED,출발,N,2020-06-08 00:05:00,2020-06-08 23:55:00
14779,OZ8993,아시아나항공,CJU,GMP,제주,서울/김포,2200,2141.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00
14780,OZ8995,아시아나항공,CJU,GMP,제주,서울/김포,2230,2216.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00

In [5]:
# 1. null 제거
NA = flight['changed_time'].isnull()
NA_INDEX = NA[NA==True].index
NA_INDEX

flight.drop(NA_INDEX,inplace=True)

In [6]:
# 2. 형식 바꾸기 ( 시간 차를 구하기 위해서)
flight['scheduled_time2'] = flight.scheduled_time.apply(lambda x: str(x)[:-2]+'-'+ str(x)[-2:])

In [7]:
import math
#float->int형으로 교환
flight['changed_time2'] = flight.changed_time.apply(lambda x: math.trunc(x))

In [8]:
flight.changed_time2 = flight.changed_time2.apply(lambda x: str(x)[:-2]+'-'+str(x)[-2:])

In [9]:
flight.head()

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date,scheduled_time2,changed_time2
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,6-30,6-37
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,6-40,6-54
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,7-00,6-58
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7-00,7-07
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,7-15,7-02

In [10]:
# 시간 차이 구하기
import datetime
flight.scheduled_time2=flight.scheduled_time2.apply(lambda x: datetime.datetime.strptime(x, '%H-%M'))
flight.changed_time2 = flight.changed_time2.apply(lambda x:datetime.datetime.strptime(x, '%H-%M'))

In [11]:
flight['diff'] = flight.changed_time2 - flight.scheduled_time2

In [12]:
flight['diff'] = flight['diff'].apply(lambda x: x.total_seconds())//60

In [13]:
flight['diff'] = flight['diff'].apply(lambda x: math.trunc(x))

In [14]:
del flight['scheduled_time2']
del flight['changed_time2']

In [15]:
flight.head()

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date,diff
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,14
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-2
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-13

In [16]:
# 1~5분, 5~10분 단위로, 10~20분 단위로, 20~30분
# 0일때는 (delay가 없다 ) : delay_section 이 0
# 1~5분 : delay_section 이 1이다
# 5~10분 : delay_section 이 2이다
# 10~20분 : delay_Section 이 3이다
# 20~30분 : delay_section 이 4이다.
# 결항 : 5번 그룹
# 30분 이상은 6번그룹

In [17]:
flight['delay_section'] = 6 # 변수를 미리 생성

In [18]:
# delay 없다. => 0번집단
flight.loc[(flight['diff']<=0), ['delay_section']] = 0

In [19]:
#delay 가 1분부터 5분까지 => 1번집단
flight.loc[(flight['diff']>0)& (flight['diff']<=5), ['delay_section']] = 1

In [20]:
#delay 가 6분부터 10분까지 =>2번집단

flight.loc[(flight['diff']>5)& (flight['diff']<=10), ['delay_section']] = 2

In [21]:
#delay 가 11분부터 20분까지 =>3번집단
flight.loc[(flight['diff']>10)& (flight['diff']<=20), ['delay_section']] = 3

In [22]:
#delay 가 21분부터 30분까지 =>4번집단
flight.loc[(flight['diff']>20)& (flight['diff']<=30), ['delay_section']] = 4

In [23]:
# 결향인 것은 5번 집단으로 한다.
flight.loc[(flight['flight_status_kor']=='결항'), ['delay_section']] = 5

In [24]:
# delay 가 30분 이후는 6번집단

In [25]:
flight

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date,diff,delay_section
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,14,3
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-2,0
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14776,KE1273,대한항공,CJU,GMP,제주,서울/김포,2140,2126.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-14,0
14777,7C147,제주항공,CJU,GMP,제주,서울/김포,2145,2135.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-10,0
14778,TW9816,티웨이항공,CJU,TAE,대구,제주,2155,2158.0,O,DEPARTED,출발,N,2020-06-08 00:05:00,2020-06-08 23:55:00,3,1
14779,OZ8993,아시아나항공,CJU,GMP,제주,서울/김포,2200,2141.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-19,0
14780,OZ8995,아시아나항공,CJU,GMP,제주,서울/김포,2230,2216.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-14,0

In [26]:
a = flight.copy()

In [29]:
a['flight_num', 'airline_name', 'city_code','arrived_airport_name', 'boarding_airport_name',
 '']

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date,diff,delay_section
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,14,3
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-2,0
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14776,KE1273,대한항공,CJU,GMP,제주,서울/김포,2140,2126.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-14,0
14777,7C147,제주항공,CJU,GMP,제주,서울/김포,2145,2135.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-10,0
14778,TW9816,티웨이항공,CJU,TAE,대구,제주,2155,2158.0,O,DEPARTED,출발,N,2020-06-08 00:05:00,2020-06-08 23:55:00,3,1
14779,OZ8993,아시아나항공,CJU,GMP,제주,서울/김포,2200,2141.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-19,0
14780,OZ8995,아시아나항공,CJU,GMP,제주,서울/김포,2230,2216.0,I,ARRIVED,도착,N,2020-06-08 00:05:00,2020-06-08 23:55:00,-14,0

In [45]:
# 일별 지연횟수 확인하고자한다

In [46]:
#flight['create_date'][0].month

4

In [48]:
flight['day'] = flight['create_date'].apply(lambda x: str(x.month) + '-' + str(x.day))

In [49]:
flight.head()

,flight_num,airline_name,airport_code,city_code,arrived_airport_name,boarding_airport_name,scheduled_time,changed_time,inout_code,flight_status_eng,flight_status_kor,delay_yn,create_date,update_date,diff,delay_section,day
0,OZ8900,아시아나항공,CJU,GMP,서울/김포,제주,630,637.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2,4-27
1,OZ8902,아시아나항공,CJU,GMP,서울/김포,제주,640,654.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,14,3,4-27
2,RS901,에어서울,CJU,GMP,제주,서울/김포,700,658.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-2,0,4-27
3,KE1204,대한항공,CJU,GMP,서울/김포,제주,700,707.0,O,DEPARTED,출발,N,2020-04-27 11:06:00,\N,7,2,4-27
4,OZ8901,아시아나항공,CJU,GMP,제주,서울/김포,715,702.0,I,ARRIVED,도착,N,2020-04-27 11:06:00,\N,-13,0,4-27

In [101]:
# 일별 전체 비행 횟수 도수 분포표
flight_count = flight.groupby(by=['day'], as_index=False).count()
flight_count = flight_count.iloc[:,:2]
flight_count.set_index(flight_count['day'],inplace=True)
flight_count.drop('day',axis=1 , inplace=True)

In [104]:
# 도착 지연된 비행 횟수를 도수분포표로 표현한다. ( diff가 양수인게 도착이 예상보다 지연된 것이다 ) 
arrive_delay = flight[flight['diff']>0]
arrive_delay_count = arrive_delay.groupby(by=['day'], as_index=False).count()
arrive_delay_count = arrive_delay_count.iloc[:,:2]
arrive_delay_count.set_index(arrive_delay_count['day'],inplace=True)
arrive_delay_count.drop('day',axis=1 , inplace=True)

      flight_num
day
4-27         169
4-28         178
4-29         257
4-30         345
5-1          271

In [106]:
# 출발 지연된 비행 횟수를 도수분포표로 표한한다 ( 지연 Y 라고 표시된 것이 출발 지연된 것이다 ) 
depart_delay = flight[flight['delay_yn']=="Y"]
depart_delay_count = depart_delay.groupby(by=['day'], as_index=False).count()
depart_delay_count = depart_delay_count.iloc[:,:2]
depart_delay_count.set_index(depart_delay_count['day'],inplace=True)
depart_delay_count.drop('day',axis=1 , inplace=True)
#depart_delay_count.head()

In [116]:
df = pd.merge(flight_count,arrive_delay_count, left_index=True, right_index=True, how='left' )
df = pd.merge(df, depart_delay_count,left_index=True, right_index=True, how='left' )

In [126]:
df.columns = ["total_flight_num", "arrive_delay_count", "depart_delay_count"] 
#전체 비행횟수, 도착지연횟수, 출발지연횟수 순으로 표시

In [132]:
df.to_excel("count.xlsx")